rootProject.name = 'WebaziUssdApp'

apply from: new File(["node", "--print", "require.resolve('expo/package.json')"].execute(cwd: rootDir).text.trim(), "../scripts/autolinking.gradle")
applyNativeModulesSettingsGradle(settings)

include ':app'

if (settings.hasProperty("newArchEnabled") && settings.newArchEnabled == "true") {
    include(":ReactAndroid")
    project(":ReactAndroid").projectDir = new File(
        [
            "node",
            "--print",
            'require.resolve("react-native/package.json")'
        ].execute(cwd: rootDir).text.trim(),
        "../ReactAndroid"
    )
}
