/**
 * Decodes the compact account reference generated by the Webazi websites
 * (webaziairtime.vercel.app, webaziairtimehub.vercel.app) back into
 * {network, amount, phone}. This is the counterpart of buildAccountRef()
 * in each site's submitOrder().
 *
 * Format (10 chars, fits Safaricom's 12-char STK AccountReference limit):
 *   [1] network prefix   S = Safaricom, A = Airtel
 *   [3] airtime amount   KES, base36, zero-padded (covers up to 46,655)
 *   [6] phone number     last 9 digits (leading 0 dropped), base36,
 *                        zero-padded (covers up to ~2.17 billion)
 *
 * This is what's actually deliverable — the amount is the 100% airtime
 * value, not whatever was discounted/paid, so delivery never has to trust
 * the paid amount shown elsewhere in the SMS.
 */

import { normalizeToLocal } from './phone';

export type DecodedRef = {
  network: 'safaricom' | 'airtel';
  amount: number;
  phone: string; // local format, e.g. 0735830024
};

const REF_PATTERN = /^([SA])([0-9A-Z]{3})([0-9A-Z]{6})$/;

export function decodeAccountRef(ref: string): DecodedRef | null {
  const match = ref.trim().toUpperCase().match(REF_PATTERN);
  if (!match) return null;

  const [, prefix, amtCode, numCode] = match;
  const amount = parseInt(amtCode, 36);
  const numDigits = parseInt(numCode, 36).toString().padStart(9, '0');

  if (!Number.isFinite(amount) || amount <= 0) return null;
  if (numDigits.length !== 9) return null;

  return {
    network: prefix === 'A' ? 'airtel' : 'safaricom',
    amount,
    phone: '0' + numDigits,
  };
}

/**
 * Pulls the account reference out of an M-PESA confirmation SMS.
 * Two phrasings appear in the wild for the exact same field:
 *   - "for account XXXXXXXXXX"    (seen on some STK/Till confirmations)
 *   - "Account Number XXXXXXXXXX" (seen on Paybill/Utility confirmations)
 * A compact webazi ref (buildAccountRef()'s S/A + base36 amount + base36
 * phone) can land in either phrasing depending on how the payment was
 * made, so both must be tried here — otherwise a perfectly decodable
 * ref falls through to decodePaybillSms() (which only accepts a plain
 * digits-only phone number) and ends up Unmatched.
 * Returns null if the SMS has no account reference at all (e.g. it's
 * not a till/paybill payment).
 */
export function extractAccountRef(smsBody: string): string | null {
  const match = smsBody.match(/(?:for account|Account Number)\s+([A-Za-z0-9]+)/i);
  return match ? match[1] : null;
}

export type DecodedPaybill = {
  network: 'safaricom' | 'airtel';
  amount: number;
  phone: string; // local format, e.g. 0729914983
  ref: string; // e.g. "S0729914983" — for display/logging alongside the receipt
};

const PAYBILL_ACCOUNT_PATTERN = /Account Number\s+([SA])\s*(\d{9,10})/i;
const PAYBILL_AMOUNT_PATTERN = /Ksh\s*([\d,]+(?:\.\d+)?)\s+received/i;

/**
 * Decodes a manual Paybill payment confirmation SMS — the shape you get
 * when a customer pays your Paybill directly and types their own phone
 * number into the Account Number field, prefixed with S (Safaricom) or
 * A (Airtel) so we know which network to dial from:
 *
 *   "UHQO43V4WF Confirmed. on 26/8/26 at 4:09 PM Ksh100.00 received from
 *    JOAB IRUNGU NDEGO 254729914983. Account Number S0729914983 New
 *    Utility balance is Ksh100.00"
 *
 * This is structurally different from decodeAccountRef() above: there's
 * no compact generated ref, just a raw phone number and the paid amount
 * stated directly in the SMS. Returns null if either piece is missing
 * or unparseable — callers should fall back to the "unmatched" bucket.
 */
export function decodePaybillSms(smsBody: string): DecodedPaybill | null {
  const acctMatch = smsBody.match(PAYBILL_ACCOUNT_PATTERN);
  if (!acctMatch) return null;

  const [, prefix, rawNumber] = acctMatch;
  const phone = normalizeToLocal(rawNumber);
  if (!phone) return null;

  const amtMatch = smsBody.match(PAYBILL_AMOUNT_PATTERN);
  if (!amtMatch) return null;

  const amount = Math.round(parseFloat(amtMatch[1].replace(/,/g, '')));
  if (!Number.isFinite(amount) || amount <= 0) return null;

  return {
    network: prefix.toUpperCase() === 'A' ? 'airtel' : 'safaricom',
    amount,
    phone,
    ref: `${prefix.toUpperCase()}${rawNumber.replace(/\D/g, '')}`,
  };
}

/**
 * Pulls the M-PESA receipt code from the start of a confirmation SMS
 * (e.g. "UHOO43KO9X Confirmed. You have received..."). Purely for
 * display/reconciliation — not used for decoding.
 */
export function extractReceipt(smsBody: string): string | null {
  const match = smsBody.trim().match(/^([A-Z0-9]{8,12})\s+Confirmed/i);
  return match ? match[1].toUpperCase() : null;
}

/**
 * Normalizes a local (0...) phone number to 2547.../2541....
 * @deprecated USSD dialing now uses local format directly (see services/phone.ts
 * and sambaza.ts) — kept only so nothing that still imports this breaks.
 */
export function toMsisdn(localPhone: string): string {
  if (localPhone.startsWith('0')) return '254' + localPhone.slice(1);
  return localPhone;
}
