/**
 * Decodes the compact account reference generated by the Webazi websites
 * (webaziairtime.vercel.app, webaziairtimehub.vercel.app) back into
 * {network, amount, phone}. This is the counterpart of buildAccountRef()
 * in each site's submitOrder().
 *
 * Format (10 chars, fits Safaricom's 12-char STK AccountReference limit):
 *   [1] network prefix   S = Safaricom, A = Airtel
 *   [3] airtime amount   KES, base36, zero-padded (covers up to 46,655)
 *   [6] phone number     last 9 digits (leading 0 dropped), base36,
 *                        zero-padded (covers up to ~2.17 billion)
 *
 * This is what's actually deliverable — the amount is the 100% airtime
 * value, not whatever was discounted/paid, so delivery never has to trust
 * the paid amount shown elsewhere in the SMS.
 */

export type DecodedRef = {
  network: 'safaricom' | 'airtel';
  amount: number;
  phone: string; // local format, e.g. 0735830024
};

const REF_PATTERN = /^([SA])([0-9A-Z]{3})([0-9A-Z]{6})$/;

export function decodeAccountRef(ref: string): DecodedRef | null {
  const match = ref.trim().toUpperCase().match(REF_PATTERN);
  if (!match) return null;

  const [, prefix, amtCode, numCode] = match;
  const amount = parseInt(amtCode, 36);
  const numDigits = parseInt(numCode, 36).toString().padStart(9, '0');

  if (!Number.isFinite(amount) || amount <= 0) return null;
  if (numDigits.length !== 9) return null;

  return {
    network: prefix === 'A' ? 'airtel' : 'safaricom',
    amount,
    phone: '0' + numDigits,
  };
}

/**
 * Pulls the "for account XXXXXXXXXX" reference out of an M-PESA
 * confirmation SMS. Returns null if the SMS has no account reference
 * (e.g. it's not a till/paybill payment at all).
 */
export function extractAccountRef(smsBody: string): string | null {
  const match = smsBody.match(/for account\s+([A-Za-z0-9]+)/i);
  return match ? match[1] : null;
}

/** Normalizes a local (0...) phone number to 2547.../2541... for USSD "pn" fields. */
export function toMsisdn(localPhone: string): string {
  if (localPhone.startsWith('0')) return '254' + localPhone.slice(1);
  return localPhone;
}